/* eslint-disable no-irregular-whitespace */
import { getServerSettingData } from "@/components/lib/getServerSettingData";
import Providers from "@/components/providers/Providers";
import QueryProviders from "@/components/providers/QueryProviders";
import { bodyFont } from "@/utils/font";
import "react-loading-skeleton/dist/skeleton.css";
import "react-photo-view/dist/react-photo-view.css";
import { Slide, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "react-tooltip/dist/react-tooltip.css";
import "./globals.css";

export async function generateMetadata() {
  const settingData = await getServerSettingData();
  const logoUrl = settingData?.data[0]?.logo || "Artisan Leather ";

  return {
    title: "Artisan Leather ",
    description: "Generated by Artisan Leather ",
    openGraph: {
      title: "Artisan Leather ",
      description: "Generated by Artisan Leather ",
      images: [
        {
          url: logoUrl,
          alt: "Artisan Leather  Preview Image",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: "Artisan Leather ",
      description: "Generated by Artisan Leather ",
      images: [logoUrl],
    },
  };
}

export default async function RootLayout({ children }) {
  const settingData = await getServerSettingData();
  const faviconUrl = settingData?.data[0]?.favicon || "/favicon.ico";

  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href={faviconUrl} // Use dynamic favicon or default
          type="image/x-icon"
        />

        {/* ✅ Meta Pixel Code */}
        {/* <Script id="meta-pixel" strategy="afterInteractive">
          {`!function(f,b,e,v,n,t,s)
          {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
          n.callMethod.apply(n,arguments):n.queue.push(arguments)};
          if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
          n.queue=[];t=b.createElement(e);t.async=!0;
          t.src=v;s=b.getElementsByTagName(e)[0];
          s.parentNode.insertBefore(t,s)}(window, document,'script',
          'https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '1006536941213561');
          fbq('track', 'PageView');`}
        </Script> */}
      </head>
      <body
        className={bodyFont.className}
        // style={{ "touch-action": "none" }}
      >
        {/* <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1006536941213561&ev=PageView&noscript=1"
          />
        </noscript> */}

        <Providers>
          <QueryProviders>
            <main>
              {children}
              <ToastContainer
                position="bottom-right"
                autoClose={1500}
                transition={Slide}
                closeOnClick
              />
            </main>
          </QueryProviders>
        </Providers>
      </body>
    </html>
  );
}
