// src/app/(frontend)/orders/order-tracking/page.js
import Contain from "@/components/common/Contain";
import OrderTracking from "@/components/orderTracking/OrderTracking";

export const metadata = {
  title: "Order Tracking",
  description: "Generated by Classic-eCommerce",
};

const OrderTrackingPage = () => {
  return (
    <Contain>
      <OrderTracking />
    </Contain>
  );
};

export default OrderTrackingPage;
